// ============ EDIT THIS FILE ONLY ============
window.SHOP = {
  name: "Quick Shop",
  owner: "Shantel Shan",
  tagline: "Hand-picked Kilimall finds, delivered to your door.",
  welcome: "Karibu! Tap what you like and order safely on Kilimall.",
  whatsapp: "254112111612",
  whatsappText: "Hi! I need help choosing something from your shop.",
  disclosure: true,
  accent: "#6D3FD0",
  accent2: "#2F6BFF",

  products: [
    { link: "https://k.kili.co/245a9" },
    { link: "https://k.kili.co/245ar" },
    { link: "https://k.kili.co/245ok" },
    { link: "https://k.kili.co/245os" },
    { link: "https://k.kili.co/245fc" },
    { link: "https://k.kili.co/2460w" },
    { link: "https://k.kili.co/2460y" },
    { link: "https://k.kili.co/2460f" },
    { link: "https://k.kili.co/2460c" },
    { link: "https://k.kili.co/24613" },
    { link: "https://k.kili.co/2461p" },
    { link: "https://k.kili.co/2461f" },
    { link: "https://k.kili.co/2461k" },
    { link: "https://k.kili.co/246e7" },
    { link: "https://k.kili.co/2461c" },
    { link: "https://k.kili.co/24623" },
    { link: "https://k.kili.co/2462y" },
    { link: "https://k.kili.co/2462p" },
    { link: "https://k.kili.co/2462f" },
    { link: "https://k.kili.co/2462k" },
    { link: "https://k.kili.co/2462c" },
    { link: "https://k.kili.co/24633" },
    { link: "https://k.kili.co/2463y" },
    { link: "https://k.kili.co/2463p" },
    { link: "https://k.kili.co/2463k" },
    { link: "https://k.kili.co/2463f" },
    { link: "https://k.kili.co/24687" },
    { link: "https://k.kili.co/2468y" },
    { link: "https://k.kili.co/2468p" },
    { link: "https://k.kili.co/2468f" },
    { link: "https://k.kili.co/24677" },
    { link: "https://k.kili.co/2467p" },
    { link: "https://k.kili.co/2467k" },
    { link: "https://k.kili.co/2467c" },
    { link: "https://k.kili.co/2466f" },
    { link: "https://k.kili.co/2465w" },
    { link: "https://k.kili.co/2465y" },
    { link: "https://k.kili.co/2465k" },
    { link: "https://k.kili.co/2465c" },
    { link: "https://k.kili.co/24663" },
    { link: "https://k.kili.co/24667" },
    { link: "https://k.kili.co/2466w" },
    { link: "https://k.kili.co/2466p" },
    { link: "https://k.kili.co/2466k" },
    { link: "https://k.kili.co/2466c" },
    { link: "https://k.kili.co/24673" },
    { link: "https://k.kili.co/2464y" },
    { link: "https://k.kili.co/2464f" },
    { link: "https://k.kili.co/2464k" },
    { link: "https://k.kili.co/2464c" },
    { link: "https://k.kili.co/2463c" },
    { link: "https://k.kili.co/24643" },
    { link: "https://k.kili.co/24647" },
    { link: "https://k.kili.co/2464w" }
    // { link: "https://k.kili.co/xxxxx", category: "Fashion", tag: "Popular" },
  ]
};
